---
- name: Seting up ntp config
  become: true
  ansible.builtin.template:
    src: templates/ntp.conf.j2
    dest: "{{ ntp_configfile }}"
    owner: "{{ ntp_configfile_user }}"
    group: "{{ ntp_configfile_group }}"
    mode: 0644
  notify: "Restart ntp daemons on {{ ansible_system }}"

- name: Create logging folder
  become: true
  ansible.builtin.file:
    path: "{{ ntp_ntpstats_dir }}"
    state: directory
    mode: 0755
    owner: ntp
    group: ntp
