---
- name: Seting up ntp config
  become: true
  ansible.builtin.template:
    src: templates/ntp.conf.j2
    dest: "{{ ntp_configfile }}"
    owner: "{{ ntp_configfile_user }}"
    group: "{{ ntp_configfile_group }}"
    mode: 0644
  notify: "Restart ntp daemons on {{ ansible_system }}"

- name: Create logging folder
  become: true
  ansible.builtin.file:
    path: "{{ ntp_ntpstats_dir }}"
    state: directory
    recurse: true
    mode: 'u=rwX,g=rX,o=rX'
    owner: "{{ ntp_user }}"
  notify: "Restart ntp daemons on {{ ansible_system }}"
